repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/pydocstyle
    rev: 4.0.0
    hooks:
      - id: pydocstyle
        files: ^src/
        args:
          - --convention=numpy
          - --add-ignore=D100,D101,D102,D104,D205,D400
