repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
      - id: black-jupyter
        files: ^notebooks/
  - repo: https://github.com/pycqa/pydocstyle
    rev: 4.0.0
    hooks:
      - id: pydocstyle
        files: ^src/
        args:
          - --convention=numpy
          - --add-ignore=D100,D101,D102,D104,D202,D205,D400
  - repo: https://github.com/iterative/dvc
    rev: main
    hooks:
      - id: dvc-pre-commit
        additional_dependencies:
          - .[all]
        language_version: python3
        stages:
          - commit
      - id: dvc-pre-push
        additional_dependencies:
          - .[all]
        language_version: python3
        stages:
          - push
      - id: dvc-post-checkout
        additional_dependencies:
          - .[all]
        language_version: python3
        stages:
          - post-checkout
        always_run: true
